"use client";
import {useState} from "react";
const nav=["Visão geral","Leads","Pipeline","Follow-ups","Propostas","Clientes","Chamados","Equipe","Chat interno"];
const stages=["Novo lead","Primeiro contato","Reunião marcada","Proposta enviada","Negociação"];
const seed=[
 {name:"Forro Novo",contact:"Carlos Mendes",service:"Tráfego pago",value:4800,stage:"Novo lead",owner:"Matheus",next:"Hoje, 15:30"},
 {name:"IntegraCare MV",contact:"Mariana Lopes",service:"Site institucional",value:7500,stage:"Primeiro contato",owner:"Ana Costa",next:"Amanhã, 10:00"},
 {name:"IMUNA Blindagens",contact:"Ricardo Alves",service:"Sistema web",value:18500,stage:"Reunião marcada",owner:"Matheus",next:"12 ago, 14:00"},
 {name:"FM Personalizados",contact:"Fernanda Melo",service:"Identidade visual",value:6200,stage:"Proposta enviada",owner:"Lucas Lima",next:"13 ago, 09:00"},
 {name:"Deubom Sports",contact:"André Santos",service:"Aplicativo",value:24000,stage:"Negociação",owner:"Ana Costa",next:"Hoje, 17:00"},
 {name:"Thiago Consultoria",contact:"Thiago de Paula",service:"Site + hospedagem",value:9800,stage:"Proposta enviada",owner:"Matheus",next:"14 ago, 11:30"}
];
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0});
const tone=(s:string)=>s.includes("Negociação")?"green":s.includes("Reunião")?"orange":s.includes("Proposta")?"blue":"purple";
export default function App(){const [page,setPage]=useState("Visão geral"),[leads,setLeads]=useState(seed),[modal,setModal]=useState(""),[toast,setToast]=useState("");const flash=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),2500)};return <div className="shell"><aside><div className="brand"><b>i5</b><span><strong>I5MEDIA</strong><small>Sales Hub</small></span></div><nav>{nav.map((n,i)=><button className={page===n?"active":""} onClick={()=>setPage(n)} key={n}><i>{["▦","◎","▥","◷","▤","♙","◈","♚","◌"][i]}</i>{n}{n==="Chamados"&&<em>4</em>}</button>)}</nav><div className="storage"><span>Armazenamento <b>68%</b></span><progress value="68" max="100"/><small>6,8 GB de 10 GB utilizados</small></div></aside><main><header><div className="search">⌕ <input placeholder="Buscar empresa, contato ou CNPJ..."/><kbd>⌘ K</kbd></div><button className="bell">♢<i/></button><div className="user"><Avatar n="Matheus Gouvea"/><span><b>Matheus Gouvea</b><small>Super administrador</small></span>⌄</div></header><section><Title page={page} add={()=>setModal("lead")} imp={()=>setModal("import")}/>{page==="Visão geral"&&<Dashboard leads={leads} go={setPage}/>} {page==="Pipeline"&&<Pipeline leads={leads} move={(name,stage)=>{setLeads(leads.map(l=>l.name===name?{...l,stage}:l));flash("Etapa atualizada com sucesso")}}/>}{page==="Leads"&&<LeadList leads={leads}/>} {page==="Follow-ups"&&<Follow leads={leads}/>} {page==="Propostas"&&<Proposals/>}{page==="Clientes"&&<Clients/>}{page==="Chamados"&&<Tickets/>}{page==="Equipe"&&<Team/>}{page==="Chat interno"&&<Chat/>}</section></main><button className="float" onClick={()=>setPage("Chat interno")}>◌<span>3</span></button>{toast&&<div className="toast">✓ {toast}</div>}{modal&&<Modal close={()=>setModal("")}>{modal==="import"?<Import done={()=>{setModal("");flash("47 contatos importados; 3 duplicados ignorados")}}/>:<LeadForm done={(l:any)=>{setLeads([l,...leads]);setModal("");flash("Lead cadastrado e atribuído")}}/>}</Modal>}</div>}
function Avatar({n}:{n:string}){return <i className="avatar">{n.split(" ").map(x=>x[0]).slice(0,2).join("")}</i>}
function Title({page,add,imp}:{page:string,add:()=>void,imp:()=>void}){const data:any={"Visão geral":["Olá, Matheus! 👋","Aqui está o panorama comercial da sua agência hoje."],Leads:["Leads e contatos","Toda a base comercial da agência em um só lugar."],Pipeline:["Pipeline de vendas","Acompanhe cada oportunidade até o fechamento."],"Follow-ups":["Follow-ups e agenda","Nenhuma oportunidade fica esquecida."],Propostas:["Propostas e orçamentos","Crie, envie e acompanhe propostas comerciais."],Clientes:["Clientes","Contratos, acessos e relacionamento em um só lugar."],Chamados:["Chamados dos clientes","Centralize as solicitações após o fechamento."],Equipe:["Equipe comercial","Metas, carteiras e produtividade."],"Chat interno":["Chat interno","Conversas privadas e canais da equipe."]};return <div className="title"><div><span>SEGUNDA-FEIRA, 10 DE AGOSTO</span><h1>{data[page][0]}</h1><p>{data[page][1]}</p></div>{["Visão geral","Leads"].includes(page)&&<div><button className="ghost" onClick={imp}>⇧ Importar Excel</button><button className="primary" onClick={add}>＋ Novo lead</button></div>}</div>}
function Dashboard({leads,go}:{leads:any[],go:(x:string)=>void}){return <><div className="stats">{[["Leads em tratamento","128","+12,5%","◎"],["Pipeline em aberto","R$ 184.500","+8,2%","◈"],["Faturamento no mês","R$ 76.800","+18,4%","↗"],["Taxa de conversão","24,8%","+3,1%","⌁"]].map((s,i)=><article key={s[0]}><i className={`stat s${i}`}>{s[3]}</i><span><small>{s[0]}</small><b>{s[1]}</b><em>↗ {s[2]} <small>vs. mês anterior</small></em></span></article>)}</div><div className="two"><article className="panel"><Head t="Desempenho comercial" s="Evolução dos últimos 6 meses" a="Últimos 6 meses⌄"/><div className="chart"><svg viewBox="0 0 600 220" preserveAspectRatio="none"><defs><linearGradient id="a" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#735bea" stopOpacity=".3"/><stop offset="1" stopColor="#735bea" stopOpacity="0"/></linearGradient></defs><path className="area" d="M0 180 C70 165 80 145 125 130 S190 150 245 95 S320 115 370 70 S450 90 500 40 S560 65 600 20 L600 220 L0 220Z"/><path className="line" d="M0 180 C70 165 80 145 125 130 S190 150 245 95 S320 115 370 70 S450 90 500 40 S560 65 600 20"/></svg><div>{["Mar","Abr","Mai","Jun","Jul","Ago"].map(x=><span key={x}>{x}</span>)}</div></div></article><article className="panel"><Head t="Funil de vendas" s="Distribuição por etapa" a="Ver pipeline →" click={()=>go("Pipeline")}/><div className="funnel">{stages.map((s,i)=><div key={s}><span>{s}</span><b><i style={{width:`${100-i*16}%`}}/></b><em>{38-i*6}</em></div>)}</div><div className="conversion"><span>Taxa de conversão geral</span><b>24,8% <em>↗ 3,1%</em></b></div></article></div><div className="lower"><article className="panel deals"><Head t="Negociações recentes" s="Últimas movimentações no pipeline" a="Ver todas →" click={()=>go("Leads")}/>{leads.slice(0,5).map(l=><div key={l.name}><span className="company"><i>{l.name[0]}</i><b>{l.name}<small>{l.service}</small></b></span><Pill s={l.stage}/><strong>{money(l.value)}</strong><span className="owner"><Avatar n={l.owner}/>{l.owner}</span><small>{l.next}</small></div>)}</article><article className="panel agenda"><Head t="Agenda de hoje" s="4 atividades pendentes" a="Ver agenda →" click={()=>go("Follow-ups")}/>{leads.slice(0,4).map((l,i)=><div key={l.name}><b>{["09:30","11:00","14:00","17:00"][i]}</b><i/><span><Pill s={i%2?"Reunião":"Follow-up"}/><strong>{l.name}</strong><small>{i%2?"Reunião comercial":"Retorno pelo WhatsApp"}</small></span></div>)}</article></div></>}
function Head({t,s,a,click}:{t:string,s:string,a:string,click?:()=>void}){return <div className="head"><span><b>{t}</b><small>{s}</small></span><button onClick={click}>{a}</button></div>}
function Pill({s}:{s:string}){return <span className={`pill ${tone(s)}`}>{s}</span>}
function Pipeline({leads,move}:{leads:any[],move:(a:string,b:string)=>void}){return <div className="kanban">{stages.map((s,i)=><div key={s}><h3><i/>{s}<em>{leads.filter(l=>l.stage===s).length}</em></h3>{leads.filter(l=>l.stage===s).map(l=><article key={l.name}><span className="logo">{l.name[0]}</span><small>{l.service}</small><h4>{l.name}</h4><p>{l.contact}</p><b>{money(l.value)}</b><footer><Avatar n={l.owner}/><span>◷ {l.next}</span></footer>{i<4&&<button onClick={()=>move(l.name,stages[i+1])}>Avançar →</button>}</article>)}</div>)}</div>}
function LeadList({leads}:{leads:any[]}){return <article className="panel table"><header><span>EMPRESA / CONTATO</span><span>SERVIÇO</span><span>ETAPA</span><span>VALOR</span><span>RESPONSÁVEL</span></header>{leads.map(l=><div key={l.name}><span className="company"><i>{l.name[0]}</i><b>{l.name}<small>{l.contact}</small></b></span><span>{l.service}</span><Pill s={l.stage}/><strong>{money(l.value)}</strong><span className="owner"><Avatar n={l.owner}/>{l.owner}</span></div>)}</article>}
function Follow({leads}:{leads:any[]}){return <div className="follow"><article className="panel"><h2>Hoje <Pill s="4 pendentes"/></h2>{leads.slice(0,5).map((l,i)=><div key={l.name}><button>✓</button><span><b>{l.name}</b><small>{i%2?"Reunião comercial":"Retorno por WhatsApp"} · {l.next}</small></span><Avatar n={l.owner}/></div>)}</article><article className="panel calendar"><h2>Agosto 2026</h2><div>{["D","S","T","Q","Q","S","S",...Array.from({length:31},(_,i)=>i+1)].map((d,i)=><span className={d===10?"today":""} key={i}>{d}</span>)}</div><p><b>3 follow-ups atrasados</b><small>Revise as atividades que passaram do prazo.</small></p></article></div>}
function Proposals(){return <><div className="stats compact">{[["Em elaboração","8"],["Enviadas","19"],["Aprovadas","12"],["Aguardando retorno","7"]].map((x,i)=><article key={x[0]}><i className={`stat s${i}`}>▤</i><span><small>{x[0]}</small><b>{x[1]}</b></span></article>)}</div><article className="panel list">{[["PROP-026","IMUNA Blindagens","Sistema web completo","R$ 18.500","Aguardando"],["PROP-025","FM Personalizados","Identidade visual + conteúdo","R$ 6.200","Enviada"],["PROP-024","Deubom Sports","Aplicativo web","R$ 24.000","Negociação"],["PROP-023","Thiago Consultoria","Site + hospedagem anual","R$ 9.800","Aprovada"]].map(x=><div key={x[0]}><b>{x[0]}<small>{x[1]}</small></b><span>{x[2]}</span><strong>{x[3]}</strong><Pill s={x[4]}/><button>•••</button></div>)}</article></>}
function Clients(){return <div className="cards">{[["Forro Novo","Tráfego pago","R$ 4.800/mês","Matheus"],["IntegraCare MV","Site institucional","R$ 7.500","Ana Costa"],["Thiago Consultoria","Site + hospedagem","R$ 9.800","Matheus"]].map(x=><article className="panel" key={x[0]}><div><i>{x[0][0]}</i><Pill s="Ativo"/></div><h2>{x[0]}</h2><p>{x[1]}</p><strong>{x[2]}</strong><hr/><small>Executivo responsável</small><b className="owner"><Avatar n={x[3]}/>{x[3]}</b><button>Abrir portal do cliente →</button></article>)}</div>}
function Tickets(){return <article className="panel list tickets">{[["#1048","Forro Novo","Ajuste na campanha do Google","Alta","Em andamento"],["#1047","IntegraCare MV","Troca de imagem no banner","Média","Aguardando cliente"],["#1046","FM Personalizados","Novo acesso ao Instagram","Baixa","Aberto"],["#1045","Thiago Consultoria","Atualização de conteúdo","Média","Concluído"]].map(x=><div key={x[0]}><b>{x[0]}</b><span><strong>{x[1]}</strong><small>{x[2]}</small></span><Pill s={x[3]}/><Pill s={x[4]}/><button>Ver chamado →</button></div>)}</article>}
function Team(){return <div className="cards team">{[["Matheus Gouvea","Super Admin","42","R$ 78.400","31%"],["Ana Costa","Executiva de vendas","38","R$ 62.300","26%"],["Lucas Lima","Executivo de vendas","34","R$ 43.800","22%"]].map((x,i)=><article className="panel" key={x[0]}><Avatar n={x[0]}/><h2>{x[0]}</h2><p>{x[1]}</p><div><span>Leads ativos<b>{x[2]}</b></span><span>Pipeline<b>{x[3]}</b></span><span>Conversão<b>{x[4]}</b></span></div><progress value={[88,72,61][i]} max="100"/><small>{[88,72,61][i]}% da meta mensal</small><button>Ver desempenho</button></article>)}</div>}
function Chat(){const [m,setM]=useState(["Bom dia, equipe! Reunião às 16h.","A proposta da FM foi atualizada."]),[v,setV]=useState("");return <div className="chat"><aside className="panel"><h3>CANAIS</h3><button className="selected"># Geral <b>2</b></button><button># Comercial</button><button># Projetos</button><h3>MENSAGENS DIRETAS</h3><button><Avatar n="Ana Costa"/>Ana Costa</button><button><Avatar n="Lucas Lima"/>Lucas Lima</button></aside><article className="panel"><header><b># Geral</b><small>3 membros</small></header><main>{m.map((x,i)=><div key={i}><Avatar n={i?"Ana Costa":"Matheus Gouvea"}/><p><b>{i?"Ana Costa":"Matheus Gouvea"}</b>{x}</p></div>)}</main><footer><input value={v} onChange={e=>setV(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&v){setM([...m,v]);setV("")}}} placeholder="Escreva uma mensagem..."/><button onClick={()=>{if(v){setM([...m,v]);setV("")}}}>➤</button></footer></article></div>}
function Modal({children,close}:{children:any,close:()=>void}){return <div className="back" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="x" onClick={close}>×</button>{children}</div></div>}
function Import({done}:{done:()=>void}){return <><label className="tag">IMPORTAÇÃO INTELIGENTE</label><h2>Carregar contatos do Excel</h2><p>Envie XLSX ou CSV. Duplicidades serão identificadas automaticamente.</p><label className="drop">⇧<b>Arraste sua planilha aqui</b><small>ou clique para selecionar · até 10 MB</small><input type="file"/></label><div className="radios"><b>Como distribuir os leads?</b><label><input type="radio" name="d" defaultChecked/> Escolher manualmente</label><label><input type="radio" name="d"/> Distribuição automática e equilibrada</label></div><button className="primary full" onClick={done}>Processar planilha</button></>}
function LeadForm({done}:{done:(x:any)=>void}){const [name,setName]=useState("");return <><label className="tag">NOVO CADASTRO</label><h2>Adicionar lead</h2><p>Preencha os dados essenciais da oportunidade.</p><label>Empresa<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome da empresa"/></label><div className="form"><label>Contato<input placeholder="Nome completo"/></label><label>Executivo<select><option>Matheus</option><option>Ana Costa</option><option>Lucas Lima</option></select></label><label>Serviço<select><option>Sites e lojas virtuais</option><option>Tráfego pago</option><option>Sistemas e aplicativos</option><option>Identidade visual e conteúdo</option><option>Hospedagem</option></select></label><label>Valor estimado<input type="number" placeholder="0,00"/></label></div><button className="primary full" onClick={()=>name&&done({name,contact:"Novo contato",service:"Sites e lojas virtuais",value:0,stage:"Novo lead",owner:"Matheus",next:"Sem agendamento"})}>Cadastrar lead</button></>}
