create extension if not exists pgcrypto;

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;

create table private.admin_allowlist (
  email text primary key check (email = lower(email)),
  created_at timestamptz not null default now()
);

insert into private.admin_allowlist (email)
values ('i5mediaagencia@gmail.com')
on conflict (email) do nothing;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text not null default '',
  role text not null default 'client' check (role in ('super_admin', 'executive', 'client')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.services (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.companies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  legal_name text,
  cnpj text,
  email text,
  phone text,
  website text,
  address text,
  source text not null default 'Manual',
  stage text not null default 'Novo lead' check (stage in ('Novo lead', 'Primeiro contato', 'Reunião marcada', 'Proposta enviada', 'Negociação', 'Ganho', 'Perdido')),
  estimated_value numeric(12,2) not null default 0 check (estimated_value >= 0),
  owner_id uuid references public.profiles(id) on delete set null,
  client_user_id uuid unique references public.profiles(id) on delete set null,
  lost_reason text,
  closed_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index companies_cnpj_unique on public.companies (cnpj) where cnpj is not null and cnpj <> '';
create index companies_owner_id_idx on public.companies (owner_id);
create index companies_client_user_id_idx on public.companies (client_user_id);
create index companies_stage_idx on public.companies (stage);

create table public.contacts (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  name text not null,
  kind text not null default 'Responsável' check (kind in ('Dono', 'Financeiro', 'Participante', 'Responsável', 'Outro')),
  job_title text,
  email text,
  phone text,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index contacts_company_id_idx on public.contacts (company_id);

create table public.followups (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  assigned_to uuid references public.profiles(id) on delete set null,
  type text not null default 'Follow-up' check (type in ('Follow-up', 'Ligação', 'WhatsApp', 'E-mail', 'Reunião', 'Tarefa')),
  title text not null,
  notes text,
  due_at timestamptz,
  completed_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index followups_company_id_idx on public.followups (company_id);
create index followups_assigned_to_due_at_idx on public.followups (assigned_to, due_at);

create table public.proposals (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  number bigint generated by default as identity unique,
  title text not null default 'Orçamento comercial',
  status text not null default 'Rascunho' check (status in ('Rascunho', 'Enviada', 'Visualizada', 'Negociação', 'Aprovada', 'Recusada', 'Expirada')),
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  discount numeric(12,2) not null default 0 check (discount >= 0),
  total numeric(12,2) generated always as (greatest(subtotal - discount, 0)) stored,
  valid_until date,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index proposals_company_id_idx on public.proposals (company_id);
create index proposals_status_idx on public.proposals (status);

create table public.proposal_items (
  id uuid primary key default gen_random_uuid(),
  proposal_id uuid not null references public.proposals(id) on delete cascade,
  service_id uuid references public.services(id) on delete set null,
  description text not null,
  quantity numeric(10,2) not null default 1 check (quantity > 0),
  unit_price numeric(12,2) not null default 0 check (unit_price >= 0),
  total numeric(12,2) generated always as (quantity * unit_price) stored,
  created_at timestamptz not null default now()
);

create index proposal_items_proposal_id_idx on public.proposal_items (proposal_id);

create table public.documents (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  type text not null default 'Contrato' check (type in ('Contrato', 'Proposta', 'Briefing', 'Outro')),
  file_name text not null,
  storage_path text not null unique,
  mime_type text,
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  uploaded_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index documents_company_id_idx on public.documents (company_id);

create table public.tickets (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  subject text not null,
  description text not null,
  priority text not null default 'Média' check (priority in ('Baixa', 'Média', 'Alta', 'Urgente')),
  status text not null default 'Aberto' check (status in ('Aberto', 'Em andamento', 'Aguardando cliente', 'Concluído', 'Cancelado')),
  assigned_to uuid references public.profiles(id) on delete set null,
  opened_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz
);

create index tickets_company_id_idx on public.tickets (company_id);
create index tickets_assigned_to_idx on public.tickets (assigned_to);

create table public.ticket_messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (length(body) between 1 and 10000),
  created_at timestamptz not null default now()
);

create index ticket_messages_ticket_id_created_at_idx on public.ticket_messages (ticket_id, created_at);

create table public.team_messages (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid references public.profiles(id) on delete cascade,
  company_id uuid references public.companies(id) on delete set null,
  channel text not null default 'geral',
  body text not null check (length(body) between 1 and 10000),
  is_private boolean not null default false,
  created_at timestamptz not null default now(),
  check ((is_private and recipient_id is not null) or (not is_private))
);

create index team_messages_created_at_idx on public.team_messages (created_at);
create index team_messages_recipient_id_idx on public.team_messages (recipient_id);

create table public.import_batches (
  id uuid primary key default gen_random_uuid(),
  file_name text not null,
  distribution_mode text not null check (distribution_mode in ('manual', 'automatic')),
  status text not null default 'processing' check (status in ('processing', 'completed', 'failed')),
  total_rows integer not null default 0 check (total_rows >= 0),
  imported_rows integer not null default 0 check (imported_rows >= 0),
  duplicate_rows integer not null default 0 check (duplicate_rows >= 0),
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table public.company_stage_history (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  from_stage text,
  to_stage text not null,
  changed_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index company_stage_history_company_id_created_at_idx on public.company_stage_history (company_id, created_at);

create or replace function private.is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = private, auth, pg_temp
as $$
  select auth.uid() is not null
    and exists (
      select 1
      from private.admin_allowlist
      where email = lower(coalesce(auth.jwt() ->> 'email', ''))
    );
$$;

create or replace function private.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
  select auth.uid() is not null
    and exists (
      select 1 from public.profiles
      where id = auth.uid()
        and active
        and role in ('super_admin', 'executive')
    );
$$;

revoke all on function private.is_super_admin() from public;
revoke all on function private.is_staff() from public;
grant execute on function private.is_super_admin() to authenticated;
grant execute on function private.is_staff() to authenticated;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    lower(coalesce(new.email, '')),
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    case
      when exists (
        select 1 from private.admin_allowlist
        where email = lower(coalesce(new.email, ''))
      ) then 'super_admin'
      else 'client'
    end
  )
  on conflict (id) do update
  set email = excluded.email,
      full_name = case when public.profiles.full_name = '' then excluded.full_name else public.profiles.full_name end,
      updated_at = now();
  return new;
end;
$$;

revoke all on function private.handle_new_user() from public;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure private.handle_new_user();

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function private.set_updated_at() from public;

create trigger profiles_set_updated_at before update on public.profiles for each row execute procedure private.set_updated_at();
create trigger companies_set_updated_at before update on public.companies for each row execute procedure private.set_updated_at();
create trigger contacts_set_updated_at before update on public.contacts for each row execute procedure private.set_updated_at();
create trigger followups_set_updated_at before update on public.followups for each row execute procedure private.set_updated_at();
create trigger proposals_set_updated_at before update on public.proposals for each row execute procedure private.set_updated_at();
create trigger tickets_set_updated_at before update on public.tickets for each row execute procedure private.set_updated_at();

create or replace function private.log_company_stage_change()
returns trigger
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
begin
  if old.stage is distinct from new.stage then
    insert into public.company_stage_history (company_id, from_stage, to_stage, changed_by)
    values (new.id, old.stage, new.stage, auth.uid());
  end if;
  return new;
end;
$$;

revoke all on function private.log_company_stage_change() from public;

create trigger companies_log_stage_change
  after update of stage on public.companies
  for each row execute procedure private.log_company_stage_change();

alter table public.profiles enable row level security;
alter table public.services enable row level security;
alter table public.companies enable row level security;
alter table public.contacts enable row level security;
alter table public.followups enable row level security;
alter table public.proposals enable row level security;
alter table public.proposal_items enable row level security;
alter table public.documents enable row level security;
alter table public.tickets enable row level security;
alter table public.ticket_messages enable row level security;
alter table public.team_messages enable row level security;
alter table public.import_batches enable row level security;
alter table public.company_stage_history enable row level security;

revoke all on all tables in schema public from anon;
grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create policy profiles_select on public.profiles
  for select to authenticated
  using (id = auth.uid() or private.is_super_admin() or private.is_staff());

create policy profiles_admin_insert on public.profiles
  for insert to authenticated
  with check (private.is_super_admin());

create policy profiles_admin_update on public.profiles
  for update to authenticated
  using (private.is_super_admin())
  with check (private.is_super_admin());

create policy profiles_admin_delete on public.profiles
  for delete to authenticated
  using (private.is_super_admin());

create policy services_select on public.services
  for select to authenticated
  using (true);

create policy services_admin_insert on public.services
  for insert to authenticated
  with check (private.is_super_admin());

create policy services_admin_update on public.services
  for update to authenticated
  using (private.is_super_admin())
  with check (private.is_super_admin());

create policy services_admin_delete on public.services
  for delete to authenticated
  using (private.is_super_admin());

create policy companies_select on public.companies
  for select to authenticated
  using (
    private.is_super_admin()
    or owner_id = auth.uid()
    or client_user_id = auth.uid()
  );

create policy companies_insert on public.companies
  for insert to authenticated
  with check (
    private.is_super_admin()
    or (private.is_staff() and owner_id = auth.uid())
  );

create policy companies_update on public.companies
  for update to authenticated
  using (private.is_super_admin() or (private.is_staff() and owner_id = auth.uid()))
  with check (private.is_super_admin() or (private.is_staff() and owner_id = auth.uid()));

create policy companies_delete on public.companies
  for delete to authenticated
  using (private.is_super_admin());

create policy contacts_select on public.contacts
  for select to authenticated
  using (exists (select 1 from public.companies c where c.id = company_id));

create policy contacts_insert on public.contacts
  for insert to authenticated
  with check (private.is_staff() and exists (select 1 from public.companies c where c.id = company_id and (private.is_super_admin() or c.owner_id = auth.uid())));

create policy contacts_update on public.contacts
  for update to authenticated
  using (private.is_staff() and exists (select 1 from public.companies c where c.id = company_id and (private.is_super_admin() or c.owner_id = auth.uid())))
  with check (private.is_staff() and exists (select 1 from public.companies c where c.id = company_id and (private.is_super_admin() or c.owner_id = auth.uid())));

create policy contacts_delete on public.contacts
  for delete to authenticated
  using (private.is_staff() and exists (select 1 from public.companies c where c.id = company_id and (private.is_super_admin() or c.owner_id = auth.uid())));

create policy followups_select on public.followups
  for select to authenticated
  using (exists (select 1 from public.companies c where c.id = company_id));

create policy followups_insert on public.followups
  for insert to authenticated
  with check (private.is_staff() and exists (select 1 from public.companies c where c.id = company_id and (private.is_super_admin() or c.owner_id = auth.uid())));

create policy followups_update on public.followups
  for update to authenticated
  using (private.is_staff() and exists (select 1 from public.companies c where c.id = company_id and (private.is_super_admin() or c.owner_id = auth.uid())))
  with check (private.is_staff() and exists (select 1 from public.companies c where c.id = company_id and (private.is_super_admin() or c.owner_id = auth.uid())));

create policy followups_delete on public.followups
  for delete to authenticated
  using (private.is_staff() and exists (select 1 from public.companies c where c.id = company_id and (private.is_super_admin() or c.owner_id = auth.uid())));

create policy proposals_select on public.proposals
  for select to authenticated
  using (exists (select 1 from public.companies c where c.id = company_id));

create policy proposals_insert on public.proposals
  for insert to authenticated
  with check (private.is_staff() and exists (select 1 from public.companies c where c.id = company_id and (private.is_super_admin() or c.owner_id = auth.uid())));

create policy proposals_update on public.proposals
  for update to authenticated
  using (private.is_staff() and exists (select 1 from public.companies c where c.id = company_id and (private.is_super_admin() or c.owner_id = auth.uid())))
  with check (private.is_staff() and exists (select 1 from public.companies c where c.id = company_id and (private.is_super_admin() or c.owner_id = auth.uid())));

create policy proposals_delete on public.proposals
  for delete to authenticated
  using (private.is_staff() and exists (select 1 from public.companies c where c.id = company_id and (private.is_super_admin() or c.owner_id = auth.uid())));

create policy proposal_items_select on public.proposal_items
  for select to authenticated
  using (exists (select 1 from public.proposals p where p.id = proposal_id));

create policy proposal_items_insert on public.proposal_items
  for insert to authenticated
  with check (private.is_staff() and exists (select 1 from public.proposals p where p.id = proposal_id));

create policy proposal_items_update on public.proposal_items
  for update to authenticated
  using (private.is_staff() and exists (select 1 from public.proposals p where p.id = proposal_id))
  with check (private.is_staff() and exists (select 1 from public.proposals p where p.id = proposal_id));

create policy proposal_items_delete on public.proposal_items
  for delete to authenticated
  using (private.is_staff() and exists (select 1 from public.proposals p where p.id = proposal_id));

create policy documents_select on public.documents
  for select to authenticated
  using (exists (select 1 from public.companies c where c.id = company_id));

create policy documents_insert on public.documents
  for insert to authenticated
  with check (private.is_staff() and exists (select 1 from public.companies c where c.id = company_id and (private.is_super_admin() or c.owner_id = auth.uid())));

create policy documents_update on public.documents
  for update to authenticated
  using (private.is_staff() and exists (select 1 from public.companies c where c.id = company_id and (private.is_super_admin() or c.owner_id = auth.uid())))
  with check (private.is_staff() and exists (select 1 from public.companies c where c.id = company_id and (private.is_super_admin() or c.owner_id = auth.uid())));

create policy documents_delete on public.documents
  for delete to authenticated
  using (private.is_staff() and exists (select 1 from public.companies c where c.id = company_id and (private.is_super_admin() or c.owner_id = auth.uid())));

create policy tickets_select on public.tickets
  for select to authenticated
  using (exists (select 1 from public.companies c where c.id = company_id));

create policy tickets_insert on public.tickets
  for insert to authenticated
  with check (exists (select 1 from public.companies c where c.id = company_id));

create policy tickets_update on public.tickets
  for update to authenticated
  using (private.is_staff() and exists (select 1 from public.companies c where c.id = company_id))
  with check (private.is_staff() and exists (select 1 from public.companies c where c.id = company_id));

create policy ticket_messages_select on public.ticket_messages
  for select to authenticated
  using (exists (select 1 from public.tickets t where t.id = ticket_id));

create policy ticket_messages_insert on public.ticket_messages
  for insert to authenticated
  with check (sender_id = auth.uid() and exists (select 1 from public.tickets t where t.id = ticket_id));

create policy team_messages_select on public.team_messages
  for select to authenticated
  using (
    private.is_super_admin()
    or sender_id = auth.uid()
    or recipient_id = auth.uid()
    or (not is_private and private.is_staff())
  );

create policy team_messages_insert on public.team_messages
  for insert to authenticated
  with check (private.is_staff() and sender_id = auth.uid());

create policy team_messages_delete on public.team_messages
  for delete to authenticated
  using (private.is_super_admin() or sender_id = auth.uid());

create policy import_batches_select on public.import_batches
  for select to authenticated
  using (private.is_super_admin() or created_by = auth.uid());

create policy import_batches_insert on public.import_batches
  for insert to authenticated
  with check (private.is_staff() and created_by = auth.uid());

create policy import_batches_update on public.import_batches
  for update to authenticated
  using (private.is_super_admin() or created_by = auth.uid())
  with check (private.is_super_admin() or created_by = auth.uid());

create policy company_stage_history_select on public.company_stage_history
  for select to authenticated
  using (exists (select 1 from public.companies c where c.id = company_id));

insert into public.services (name) values
  ('Sites e lojas virtuais'),
  ('Tráfego pago'),
  ('Sistemas e aplicativos'),
  ('Identidade visual e conteúdo'),
  ('Hospedagem')
on conflict (name) do nothing;

insert into public.companies (name, source, stage, estimated_value) values
  ('Forro Novo', 'Indicação', 'Novo lead', 4800),
  ('IntegraCare MV', 'Site', 'Primeiro contato', 7500),
  ('IMUNA Blindagens', 'Prospecção', 'Reunião marcada', 18500),
  ('FM Personalizados', 'Instagram', 'Proposta enviada', 6200),
  ('Deubom Sports', 'Indicação', 'Negociação', 24000),
  ('Thiago Consultoria', 'Google', 'Proposta enviada', 9800);

insert into public.contacts (company_id, name, kind, is_primary)
select c.id, v.contact_name, 'Responsável', true
from (values
  ('Forro Novo', 'Carlos Mendes'),
  ('IntegraCare MV', 'Mariana Lopes'),
  ('IMUNA Blindagens', 'Ricardo Alves'),
  ('FM Personalizados', 'Fernanda Melo'),
  ('Deubom Sports', 'André Santos'),
  ('Thiago Consultoria', 'Thiago de Paula')
) as v(company_name, contact_name)
join public.companies c on c.name = v.company_name;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('contracts', 'contracts', false, 20971520, array['application/pdf'])
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create policy contracts_select on storage.objects
  for select to authenticated
  using (
    bucket_id = 'contracts'
    and exists (
      select 1
      from public.documents d
      join public.companies c on c.id = d.company_id
      where d.storage_path = name
    )
  );

create policy contracts_insert on storage.objects
  for insert to authenticated
  with check (bucket_id = 'contracts' and private.is_staff());

create policy contracts_update on storage.objects
  for update to authenticated
  using (bucket_id = 'contracts' and private.is_staff())
  with check (bucket_id = 'contracts' and private.is_staff());

create policy contracts_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'contracts' and private.is_staff());
